<?php

namespace App\Services;

use App\Enums\AssistantMode;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Stevebauman\Location\Facades\Location;

class GPT
{
    /**
     * Mode of the assistant
     *
     * @var AssistantMode
     */
    private AssistantMode $assistantMode;

    /**
     * Should assistant remember context of conversation
     *
     * @var bool
     */
    private bool $shouldRememberContext = false;

    /**
     * Token to access conversation context
     *
     * @var string
     */
    private string $apiToken;

    /**
     * Base system prompt giving the assistant directions on how to compose answers
     *
     * @var string
     */
    private string $baseSystemPrompt;

    public function __construct(AssistantMode $assistantMode)
    {
        $this->assistantMode = $assistantMode;
    }

    /**
     * Prepare city and country name from IP address
     *
     * @return array
     */
    private function getCityAndCountryName(): array
    {
        $userLocationInfo = Location::get(request()->ip());

        return array($userLocationInfo->cityName, $userLocationInfo->countryName);
    }

    /**
     * Get first line told by system to the assistant about how it should compose answers
     *
     * @return string
     */
    private function getAssistantModeSpecificSystemOrder(): string
    {
        return match ($this->assistantMode) {
            AssistantMode::INFORMATIVE => 'Jesteś asystentem pogodowym. Twoje odpowiedzi są krótkie i zwięzłe.',
            AssistantMode::CONVERSATIONAL => 'Jesteś asystentem pogodowym. Twoje odpowiedzi są dłuższe i bardziej rozbudowane.'
        };
    }

    /**
     * Ask assistant a question
     *
     * @param mixed $question
     * @param bool $generateOpenWeatherLink
     * @return string
     */
    public function ask(mixed $question, bool $generateOpenWeatherLink = false): string
    {
        $jsonData = $this->prepareQuestionJsonData($question, $generateOpenWeatherLink);

        $jsonFilePath = $this->saveQuestionFile($jsonData);

        $this->callMediator($jsonFilePath);

        $answer = $this->readAnswerJsonData($jsonFilePath);

        $this->clearFiles($jsonFilePath);

        return $answer;
    }

    /**
     * Generate voice that reads a message and saves it to public folder.
     *
     * @param string $text
     * @return void
     */
    public function generateVoice(string $text): void
    {
        $jsonData = $this->prepareVoiceJsonData($text);

        $jsonFilePath = $this->saveQuestionFile($jsonData);

        $this->callVoiceGenerator($jsonFilePath);

        $this->clearFiles($jsonFilePath);
    }

    /**
     * Let assistant remember context of the conversation
     *
     * @return $this
     */
    public function rememberContext(string $apiToken): self
    {
        $this->shouldRememberContext = true;
        $this->apiToken = $apiToken;

        return $this;
    }

    /**
     * Set up a question file, that the Python script can further process
     *
     * @param array $jsonData
     * @return string
     */
    private function saveQuestionFile(array $jsonData): string
    {
        $jsonData = json_encode($jsonData, JSON_PRETTY_PRINT);

        $jsonFilePath = storage_path('app/jsons') . '/' . Str::random() . '_question.json';

        $fp = fopen($jsonFilePath, 'w');
        fwrite($fp, $jsonData);
        fclose($fp);

        return $jsonFilePath;
    }

    /**
     * Call Python script that will process the question file
     *
     * @param string $jsonFilePath
     * @return void
     */
    private function callMediator(string $jsonFilePath): void
    {
        exec('cd .. && . venv/bin/activate && python3 main.py ' . $jsonFilePath, $output, $returnCode);
    }

    /**
     * Call Python script that will generate a voice based on a question file
     *
     * @param string $jsonFilePath
     * @return void
     */
    private function callVoiceGenerator(string $jsonFilePath): void
    {
        exec('cd .. && . venv/bin/activate && python3 voice.py ' . $jsonFilePath, $output, $returnCode);
    }

    /**
     * Get path to the answer file generated by Python script
     *
     * @param string $jsonFilePath
     * @return string
     */
    private function getAnswerFilePath(string $jsonFilePath): string
    {
        $pathWithoutExtension = explode('.', $jsonFilePath)[0];

        return $pathWithoutExtension . '_answer.json';
    }

    /**
     * Get context file path
     *
     * @return string|null
     */
    private function getContextFilePath(): string|null
    {
        if($this->shouldRememberContext) {
            $contextFilePath =  storage_path('app/conversations') . '/' . $this->apiToken . '_' . now()->format("Ymd") . '_context.json';

            if(!file_exists($contextFilePath)) {
                $fp = fopen($contextFilePath, 'w');
                fwrite($fp, json_encode([]));
                fclose($fp);
            }

            return $contextFilePath;
        }

        return null;
    }

    /**
     * Prepare data in JSON format to be saved in a file
     *
     * @param mixed $question
     * @param bool $generateOpenWeatherLink
     * @return array|null
     */
    private function prepareQuestionJsonData(mixed $question, bool $generateOpenWeatherLink): ?array
    {
        if($question instanceof UploadedFile) {
            $jsonData = [
                'type' => 'audio',
                'assistant-mode-prompt' => $this->getAssistantModeSpecificSystemOrder(),
                'should-remember-context' => $this->shouldRememberContext,
                'context-filepath' => $this->getContextFilePath(),
                'generate-weather-link' => $generateOpenWeatherLink,
            ];

            $fileName = Str::random() . '.' . $question->getClientOriginalExtension();

            $jsonData['question'] = 'storage/app/' . $question->storeAs('audio', $fileName);
        } elseif (is_string($question)) {
            $jsonData = [
                'type' => 'text',
                'assistant-mode-prompt' => $this->getAssistantModeSpecificSystemOrder(),
                'question' => $question,
                'should-remember-context' => $this->shouldRememberContext,
                'context-filepath' => $this->getContextFilePath(),
                'generate-weather-link' => $generateOpenWeatherLink,
            ];
        } else {
            return null;
        }

        return $jsonData;
    }

    /**
     * Prepare voice data in JSON format to be saved in a file
     *
     * @param string $message
     * @return string[]
     */
    private function prepareVoiceJsonData(string $message): array
    {
        return [
            'message' => $message,
        ];
    }

    /**
     * Read data from answer file
     *
     * @param string $jsonFilePath
     * @return mixed
     */
    private function readAnswerJsonData(string $jsonFilePath): mixed
    {
        $answerFilePath = $this->getAnswerFilePath($jsonFilePath);

        $fp = fopen($answerFilePath, 'r');
        $fileText = fread($fp, filesize($answerFilePath));
        fclose($fp);

        return json_decode($fileText, true);
    }

    /**
     * Remove question and answer files
     *
     * @param string $jsonFilePath
     * @return void
     */
    private function clearFiles(string $jsonFilePath): void
    {
        $answerFile = $this->getAnswerFilePath($jsonFilePath);

        if(file_exists($answerFile)) {
            unlink($answerFile);
        }

        unlink($jsonFilePath);
    }
}
