<?php

namespace App\Services;

use App\Enums\AssistantMode;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class GPT
{
    /**
     * Mode of the assistant
     *
     * @var AssistantMode
     */
    private AssistantMode $assistantMode;

    /**
     * Should assistant remember context of conversation
     *
     * @var bool
     */
    private bool $shouldRememberContext = false;

    /**
     * Token to access conversation context
     *
     * @var string
     */
    private string $apiToken;

    public function __construct(AssistantMode $assistantMode)
    {
        $this->assistantMode = $assistantMode;
    }

    /**
     * Get first line told by system to the assistant about how it should compose answers
     *
     * @return string
     */
    private function getAssistantModeSpecificSystemOrder(): string
    {
        return match ($this->assistantMode) {
            AssistantMode::INFORMATIVE => 'Jesteś pomocnym asystentem. Twoje odpowiedzi są krótkie i zwięzłe.',
            AssistantMode::CONVERSATIONAL => 'Jesteś pomocnym asystentem. Twoje odpowiedzi są dłuższe i bardziej rozbudowane.'
        };
    }

    /**
     * Ask assistant a question
     *
     * @param mixed $question
     * @return string
     */
    public function ask(mixed $question): string
    {
        Log::info($this->getAssistantModeSpecificSystemOrder());
        if($question instanceof UploadedFile) {
            $jsonData = [
                'type' => 'audio',
                'assistant-mode-prompt' => $this->getAssistantModeSpecificSystemOrder(),
                'should-remember-context' => $this->shouldRememberContext,
                'context-filepath' => $this->getContextFilePath(),
            ];

            $fileName = Str::random() . '.' . $question->getClientOriginalExtension();

            $jsonData['question'] = 'storage/app/' . $question->storeAs('audio', $fileName);
        } elseif (is_string($question)) {
            $jsonData = [
                'type' => 'text',
                'assistant-mode-prompt' => $this->getAssistantModeSpecificSystemOrder(),
                'question' => $question,
                'should-remember-context' => $this->shouldRememberContext,
                'context-filepath' => $this->getContextFilePath(),
            ];
        } else {
            return false;
        }

        $jsonFilePath = $this->saveQuestionFile($jsonData);

        $this->callMediator($jsonFilePath);

        $answerFilePath = $this->getAnswerFilePath($jsonFilePath);

        $fp = fopen($answerFilePath, 'r');
        $fileText = fread($fp, filesize($answerFilePath));
        fclose($fp);

        unlink($this->getAnswerFilePath($jsonFilePath));
        unlink($jsonFilePath);

        return json_decode($fileText, true)['choices'][0]['message']['content'];
    }

    /**
     * Let assistant remember context of the conversation
     *
     * @return $this
     */
    public function rememberContext(string $apiToken): self
    {
        $this->shouldRememberContext = true;
        $this->apiToken = $apiToken;

        return $this;
    }

    /**
     * Set up a question file, that the Python script can further process
     *
     * @param array $jsonData
     * @return string
     */
    private function saveQuestionFile(array $jsonData): string
    {
        $jsonData = json_encode($jsonData, JSON_PRETTY_PRINT);

        $jsonFilePath = storage_path('app/jsons') . '/' . Str::random() . '_question.json';

        $fp = fopen($jsonFilePath, 'w');
        fwrite($fp, $jsonData);
        fclose($fp);

        return $jsonFilePath;
    }

    /**
     * Call Python script that will process the question file
     *
     * @param string $jsonFilePath
     * @return void
     */
    private function callMediator(string $jsonFilePath): void
    {
        exec('cd .. && . venv/bin/activate && python3 main.py ' . $jsonFilePath, $output, $returnCode);
    }

    /**
     * Get path to the answer file generated by Python script
     *
     * @param string $jsonFilePath
     * @return string
     */
    private function getAnswerFilePath(string $jsonFilePath): string
    {
        $pathWithoutExtension = explode('.', $jsonFilePath)[0];

        return $pathWithoutExtension . '_answer.json';
    }

    /**
     * Get context file path
     *
     * @return string|null
     */
    private function getContextFilePath(): string|null
    {
        if($this->shouldRememberContext) {
            $contextFilePath =  storage_path('app/conversations') . '/' . $this->apiToken . '_' . now()->format("Ymd") . '_context.json';

            if(!file_exists($contextFilePath)) {
                $fp = fopen($contextFilePath, 'w');
                fwrite($fp, json_encode([]));
                fclose($fp);
            }

            return $contextFilePath;
        }

        return null;
    }
}
